
USE EagleWallet;
GO;

CREATE TABLE [dbo].[MealPlans](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	CurrentBalance INT NOT NULL DEFAULT 0,
	MaxBalance INT NOT NULL DEFAULT 0,
	ExpirationDate DATE NOT NULL DEFAULT DATEADD(YEAR, 1, CAST(GETDATE() AS DATE)),
)
GO
ALTER TABLE [dbo].[MealPlans] ADD  CONSTRAINT [PK_MealPlans] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_MealPlans_UserId] ON [dbo].[MealPlans]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MealPlans]  WITH CHECK ADD  CONSTRAINT [FK_MealPlans_Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[MealPlans] CHECK CONSTRAINT [FK_MealPlans_Users_UserId]
GO